version: "3"

services:
  localstack:
    image: "localstack/localstack:latest"
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - SERVICES=sqs
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
    volumes:
      - ./.localstack:/docker-entrypoint-initaws.d/init.sh
